jobs:
- name: deploy-github-teams
  plan:
  - aggregate:
    - get: pgr301-infra-as-code
      trigger: true
  - task: apply
    file: pgr301-infra-as-code/concourse/tasks/terraform/task.yml
    input_mapping: {source: pgr301-infra-as-code}
    params:
      github_token: 70a3ff58158108b21e425208fb87f3077cb5bb12
      command: apply
      directories: |
          .
resources:

- name: pgr301-infra-as-code
  type: git
  source:
    uri: https://github.com/kveola13/pgr301-infra-as-code.git
    branch: master